<br><br><br>
<div style="align:center;margin-left: 50px;">                 	
<img src="/images/kontakt.jpg" style="width: 300px;height: auto;float: right;padding-right: 100px ;border-radius: 5%;"/>
    <!-- contact form -->
    <?php echo $this->form; ?>
<!--/ contact form -->
    </div>

</br><br>
<div style="margin-left:330px">
    <h2>Pronadjite nas na mapi :</h2></div>

<br>



    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2832.746046481134!2d20.489459115408!3d44.76559368780558!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475a70e493c40479%3A0x99c73d0cfa69a7a5!2z0JHRgNCw0ZvQtSDQiNC10YDQutC-0LLQuNGbIDE1NSwg0JHQtdC-0LPRgNCw0LQgMTEwMTA!5e0!3m2!1ssr!2srs!4v1473090878618" width="100%" height="350" frameborder="0" style="border:0;" allowfullscreen></iframe>