<h5 style="color:red">srediti cenovnik, ne treba da menja naziv smestaja...i glupo je da se unosi samo cena..kad kod pravljenja
aranzmana mora da se izabere cena...</h5>
<div style="align:center;margin-left: 50px;">
<?php echo $this->form; ?>
    <br><br>
<div class="table-responsive">
        <table class="table">
            <thead>
                <tr>

        <th>
            <i>Smestaj</i>
        </th>
        <th>
            <i> Cena </i>
        </th>
        <th>
            <i> Obriši </i>
        </th>
        <th>
            <i>Izmeni </i>
        </th>
    </tr>
            </thead>
            <tbody>
    <?php
    foreach ($this->dohvati_cenovnik as $ds) {
        echo '<tr class="table-striped">';
        echo '<td class="opis_smestaja">';
        echo $ds['smestaj'];
        echo '</td>';
        echo '<td class="cena_smestaja">';
        echo $ds['cena'];
        echo '</td>';
        echo '<td>';
        echo '<a href="/administracija/obrisi-cenu/idCenovnik/' . $ds['idCenovnik'] . '" onclick="return
confirm(' . "'Da li ste sigurni?'" . ');">Obriši</a>';
        echo '</td>';
        echo '<td>';
        echo '<a class="edit" href="javascript:void(0);">Izmeni</a> <button class="save" style="display:none;" idCenovnik="save_'.$ds['idCenovnik'].'">Zapamti</button>';
        echo '</td>';

        echo '</tr>';
    }
    ?></tbody>
</table>

</div>

<br><br><br>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $('.edit').click(function(){
        $(this).hide();
        $(this).parent().find(".save").show();
        
        var smestaj = $(this).parent().parent().find('.opis_smestaja');
        var cena = $(this).parent().parent().find('.cena_smestaja');
        
        
        smestaj.html('<textarea name="smestaj" class="opis_smestaja" style="width:100%;height:100px;">'+smestaj.html()+'</textarea>');
        cena.html('<textarea name="cena" class="cena_smestaja" style="width:100%;height:100px;">'+cena.html()+'</textarea>');
    });
    
    $('.save').click(function(){
        var save = $(this);
        var smestaj = $(this).parent().parent().find('.opis_smestaja');
        var cena = $(this).parent().parent().find('.cena_smestaja');
     
        
        var idCenovnik = save.attr('idCenovnik').split('_');
        
        $.post("/administracija/izmeni-cenu", { idCenovnik: idCenovnik[1], smestaj: smestaj.find("textarea").val(), cena: cena.find("textarea").val()}, function(data){
            if(data){
                alert("Cenovnik je uspesno izmenjen."); 
                smestaj.html(smestaj.find("textarea").val());
                cena.html(cena.find("textarea").val());
                

                save.hide();
                save.parent().find(".edit").show();
            }else{
                alert("Nije uneto!");
            }
            
            
        });
       
    });
</script>