<!-- /. ROW  --> 
<div class="row text-center pad-top">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/aranzmani/"><i class="fa fa-circle-o-notch fa-5x"></i>ARANZMANI</a>
        </div>
    </div> 


    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/rezervacije/"><i class="fa fa-envelope-o fa-5x"></i>REZERVACIJE</a>
        </div>


    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/korisnici/"><i class="fa fa-users fa-5x"></i>KORISNICI</a>
        </div>


    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/smestaji/"><i class="fa fa-lightbulb-o fa-5x"></i>SMESTAJ</a>
        </div>


    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/slike/"><i class="fa fa-key fa-5x"></i>SLIKE</a>
        </div>


    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a href="/administracija/ostalo/" ><i class="fa fa-comments-o fa-5x"></i>OSTALO</a>
        </div>
    </div>
</div>
<!-- /. ROW  --> 