<h1>LETO 2017</h1>
<div style="align:center;margin-left: 50px;">
    
<?php foreach ($this->leto as $stavka) {
    $small = substr($stavka['opis'], 0, 280);?>

    <div style="float:left; margin-right: 10px;"><img width="100px" height="100px"src="<?php print $stavka['thumbPutanja']; ?>"></img></div> 
    
    <h2> <?php print $stavka['smestaj']; ?></h2></br>
    <p><?php print $small; ?>...</p>
   
    
    <div style="margin-left:110px;">
        <a href="/aranzmani/prikaz-leto/idSmestaj/<?php print $stavka['idSmestaj'];?>" ><button>Opširnije</button></a><br><br>
    </div>

    <?php
}
?>
</div>



</br>
<div style="margin:0px auto 40px auto;display:block;text-align:center;clear:both;">
    <br/>
    <a href="<?php echo $this->url(array('controller' => 'aranzmani', 'action' => 'leto', 'strana' => $this->previousPage))
?>"> Predhodna </a>
       <?php echo "" . $this->currentPage . "/" . $this->countPages; ?>
    <a href="<?php echo $this->url(array('controller' => 'aranzmani', 'action' => 'leto', 'strana' => $this->nextPage))
       ?>"> Sledeća </a>
    <br/>
</div>

