<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Admin panel</title>
        <!-- BOOTSTRAP STYLES-->
        <link href="/assets/css/bootstrap.css" rel="stylesheet" />
        <!-- FONTAWESOME STYLES-->
        <link href="/assets/css/font-awesome.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
        <link href="/assets/css/custom.css" rel="stylesheet" />
        <!-- GOOGLE FONTS-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    </head>
    <body>


        <?php
        $ulogovan = Zend_Auth::getInstance();
        $user = $ulogovan->getIdentity()->idUloga;
        $userIme = $ulogovan->getIdentity()->imePrezime;
        ?>
        <div id="wrapper">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="adjust-nav">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                      <!-- <a class="navbar-brand" href="/">
                            <img src="/assets/img/logoAdventure.png" />
                        </a>-->
                    </div>


                    <?php
                    if ($ulogovan->hasIdentity() && $user == 1) {

                        $admin1 = '<a href="/administracija" title=""><i class="fa fa-desktop "></i> ADMINISTRACIJA SAJTA</a>';
                        $admin2 = '<a href="/prodaja" title=""><i class="fa fa-table "></i> PRODAJA ARANZMANA</a>';
                        $admin3= '<li><a href="/administracija/aranzmani/"><i class="fa fa-circle-o-notch fa-1x"></i>Aranzmani</a></li>
                        
                        <li><a href="/administracija/korisnici/"><i class="fa fa-users fa-1x"></i>Korisnici</a></li>
                        <li><a href="/administracija/smestaji/"><i class="fa fa-lightbulb-o fa-1x"></i>Smestaj</a></li>
                        <li><a href="/administracija/slike/"><i class="fa fa-key fa-1x"></i>Slike</a></li>
                        <li><a href="/administracija/ostalo/" ><i class="fa fa-comments-o fa-1x"></i>Ostalo</a></li>';
                    }
                    if ($ulogovan->hasIdentity() && $user == 3) {

                        $prodaja = '<a href="/prodaja" title="">PRODAJA ARANZMANA</a>';
                    }
                    if ($ulogovan->hasIdentity() && $user == 2) {

                        $putnici = '<a href="/rezervacije" title=""><i class="fa fa-edit "></i> REZERVISI ARANZMAN</a>';
                    }

                    if (!$ulogovan->hasIdentity()) {

                        $def = '<a href="/login" alt="Login">LOGIN</a>';
                        ?>

                        <?php
                    } else {

                        echo ' <span class="logout-spn" ><a href="/login/logout" alt="Logout" style="color:#fff;">LOGOUT</a>';
                        echo '<div style="color:#fff;"><b>' . $userIme . '</b></div> </span>';
                    }
                    ?>

                </div>
            </div>
            <!-- /. NAV TOP  -->
            
            <nav class="navbar-default navbar-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="main-menu">
                    
                        <li>&nbsp;</li>
                        <li><?php echo $admin1; ?></li>
                        
                        <li><?php echo $prodaja; ?></li>
                        <li><?php echo $putnici; ?></li>
                        <li><?php echo $def; ?></li>
                        <?php echo $admin3; ?>
                        <li><?php echo $admin2; ?></li>
                        <li><a href="/" style="color:orange; margin-left: 30px;">Pogledaj sajt</a></li>

                        
                    </ul>
                </div>

            </nav>
            <!-- /. NAV SIDE  -->
            <div id="page-wrapper" >
                <div id="page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <h2><?php print $this->Naslov; ?></h2>   
                        </div>
                    </div>              
                    <!-- /. ROW  -->
                    <hr />
<?php echo $this->layout()->content; ?>
                    <!-- /. ROW  -->           
                </div>
                <!-- /. PAGE INNER  -->
            </div>
            <!-- /. PAGE WRAPPER  -->
        </div>
        <div class="footer">


            <div class="row">
                <div class="col-lg-12" >
                    &copy;  2014 yourdomain.com | Design by: <a href="http://binarytheme.com" style="color:#fff;"  target="_blank">www.binarytheme.com</a>
                </div>
            </div>
        </div>


        <!-- /. WRAPPER  -->
        <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
        <!-- JQUERY SCRIPTS -->
        <script src="assets/js/jquery-1.10.2.js"></script>
        <!-- BOOTSTRAP SCRIPTS -->
        <script src="assets/js/bootstrap.min.js"></script>
        <!-- CUSTOM SCRIPTS -->
        <script src="assets/js/custom.js"></script>


    </body>
</html>
